### ISSUE TITLE
Extract Total Interaction Counts for Each Chromosome

### ISSUE THREAD

**Issue by MogicianEik** [bxlab/hifive#13]
Hi, I am just curious that is there an easy way to extract the total interaction counts for each chromosome?

**Comment by msauria** [comment]
There is not a command line way of doing it, but you could use the following script:
`python -c "import hifive; import numpy; hic=hifive.HiC('YOUR_PROJECT'); counts=numpy.zeros(hic.fends['chromosomes'].shape[0], dtype=numpy.dtype([('chr', hic.fends['chromosomes'].dtype), ('cis', numpy.int32), ('trans', numpy.int32)])); counts['chr']=hic.fends['chromosomes'][...]; chroms=hic.fends['fends']['chr'][...]; counts['cis']=numpy.bincount(chroms[hic.data['cis_data'][:, 0]], minlength=counts.shape[0]); counts['trans']=numpy.bincount(chroms[hic.data['trans_data'][:, 0]], minlength=counts.shape[0]); counts['trans']+=numpy.bincount(chroms[hic.data['trans_data'][:, 1]], minlength=counts.shape[0]); print counts;"`
