### ISSUE TITLE
a small striping issue

### ISSUE THREAD

**Issue by sirusb** [bxlab/hifive#2]
Hi, 
First thank you for the great package.

I think there is a small problem in the code when reading RAW format data

in line 194 and 195.
https://github.com/bxlab/hifive/blob/819bc8af526c2ab36ec1d44a10a06006e66043c2/hifive/hic_data.py#L194

Shouldn't it be 

```
 temp[0] = temp[0].strip('chr')
 temp[3] = temp[3].strip('chr')
```

I tried with a file in the following format 

```
chr1	10008	+	chr1	10108	-
chr1	10008	+	chr1	234897	-
chr1	12436	+	chr1	12886	-
chr1	12448	+	chr1	12832	-
chr1	12461	+	chr1	12879	-
chr1	12686	+	chr1	62882	+
chr1	12851	+	chr1	13308	-
```

but I got 0 loaded reads.

Thanks in advance

**Comment by msauria** [comment]
Thanks for pointing this out. I actually had come across this just the other day and have only now gotten around to pushing a new lease including this fix.

Good catch.
