### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by LI-Qinyao** [bxlab/hifive#23]
Hi, I have a problem when installing the hifive package.
The error message is RuntimeError: Python version 2.7+ is required. But my python version is 3.7.11. Please see the image.
<img width="376" alt="Screenshot 2024-02-01 at 11 17 35 AM" src="https://github.com/bxlab/hifive/assets/91313066/886cfb85-ab6e-42b0-8638-ea3a1d87ef6e">

I check the install.py file. Is it true that only python version > 2.7 but < 3.0 is valid?

**Comment by msauria** [comment]
The issue is that HiFive currently only works with Python2. I am porting the code to be Python3 compatible and hope to have it up in the development branch shortly.

**Comment by msauria** [comment]
HiFive has been updated to Python3. If you download the latest version from github, you should be able to install with Python3.

**Comment by LI-Qinyao** [comment]
Thank you for the update!
