### ISSUE TITLE
[Question] hifive Tweaking question 

### ISSUE THREAD

**Issue by sirusb** [bxlab/hifive#3]
Hi,
I have been recently using hifive to re-analysis the non-processed data of Rao et al, but the final results have a kind of noise. Just to ask for some suggestions maybe I am missing some paramters.

I used the following steps

```
mpirun -np 4 hifive hic-complete express -f 3 -B fend.bed --re Mbol --genome hg19 -R GSM1551559_HIC010_merged_nodups.bed -i 500 --knight-ruiz -P GSM1551559_HIC010_merged_nodups
```
I selected -f 3 as for low resolution I expect a small number of interactions in some bins. So if it has at least 3 interactions, I consider it as a potential signal. If I got it right, I am expecting noise to be filtered in the next steps.

When `hifive` is done I got the coordinates and plotted the heatmap using R. 

```
hifive hic-interval  -b 15000 -c 10 -d enrichment   GSM1551559_HIC010_merged_nodups.hcp $output
```

If I plot the heatmap I get the following 

<img width="405" alt="screen shot 2015-11-16 at 8 16 33 am" src="https://cloud.githubusercontent.com/assets/3537501/11172141/55ca9aa4-8c3c-11e5-93fe-a72a32e9bd23.png">

We can see the domains, but there is non-filtered noise, is it because of the `-f 3` parameter and are there other filtering criteria because I think the default value `-f 8` is a kind of extreme.

Thanks for your answer.

Regards,

**Comment by msauria** [comment]
This is definitely puzzling. Just to be clear, the -f value is filtering based on all interactions for a given fragment, not a specific bin. A value of 3 would mean that every fragment marked as valid would have reads indicating interactions with at least 3 other valid fragments. If that is what you meant, then my apologies.

I have two thoughts. First, it looks like you didn't pass a value for the -f parameter when generating the HiC interval file. This means that it defaulted to 20, so in the above heatmap you should only be seeing bins with at least 20 valid reads.

If that wasn't the problem, then my second thought is that you should update to the latest version of HiFive from the repository and reload the data. The newest version records a whole variety of metrics and I can send you the script which is under development that compiles and plots them to see if we can spot the problem. I suspect that it was the -f parameter for the HiC-interval command.

**Comment by sirusb** [comment]
Hi msauria, 
Thanks for the explanation , yeah, first I though that `-f` is for each bin as when I use for example `-f 8` I get the "Insufficient valid fend for this chromosome" message.

I will try with the new updated version, I think maybe I was passing the parameters wrong.

Thanks again.
